mysql:
  DB: mysql
  DbHost: 123.57.149.229
  DbPort: 3306
  DbUser: root
  DbPassword: mysecretpassword
  DbName: qiniu

redis:
  RedisDb: redis
  RedisAddr: 123.57.149.229:6379
  RedisPw: ruanhang
  RedisDbName: 0

es:
  Url: http://8.130.100.107:9200
  Username: elastic
  Password: 123456

application:

  Ip: localhost
  Port: 8811




qiniu:
  AccessKey: wccY3Xc1dpW5hGTYvvyYF4LnJZ1Rsk6-6mbbcxw_
  SecretKey: P11e3W-EyhiFESh0XPRhQT7Oihvj6OO48mcVig1E
  Bucket: dydemo-01
  Url: http://xzkckj.cn/

