mysql:
  DB: mysql
  DbHost: 123.57.149.229
  DbPort: 3306
  DbUser: root
  DbPassword: 
  DbName: qiniu

redis:
  RedisDb: redis
  RedisAddr: 123.57.149.229:6379
  RedisPw: 
  RedisDbName: 0

es:
  Url: http://8.130.100.107:9200
  Username: elastic
  Password: 

application:

  Ip: localhost
  Port: 8811




qiniu:
  AccessKey:
  SecretKey: 
  Bucket: dydemo-01
  Url: http://xzkckj.cn/

