mysql:
  DB: mysql
  DbHost: localhost
  DbPort: 3306
  DbUser: root
  DbPassword:
  DbName: qiniu

redis:
  RedisDb: redis
  RedisAddr: 192.168.88.130:6379
  RedisPw: rh2004..
  RedisDbName: 0

nacos:
  Ip: 127.0.0.1
  Port: 8848

application:
  ServiceName: user-center
  Ip: localhost
  Port: 8811

  video-center:
    ServiceName: vid


qiniu:
  accessKey: wccY3Xc1dpW5hGTYvvyYF4LnJZ1Rsk6-6mbbcxw_
  secretKey: P11e3W-EyhiFESh0XPRhQT7Oihvj6OO48mcVig1E
  bucket: dydemo-01
  url: http://xzkckj.cn/

