basePath: /
definitions:
  api.ErrorResponse:
    properties:
      data: {}
      error:
        type: string
      msg:
        type: string
      status:
        type: integer
    type: object
  api.Response:
    properties:
      data: {}
      error:
        type: string
      msg:
        type: string
      status:
        type: integer
    type: object
  types.FavlistAddReq:
    properties:
      favlist_id:
        type: integer
      video_id:
        type: integer
    type: object
  types.GetBarrageResp:
    properties:
      color:
        description: 弹幕颜色
        type: string
      content:
        description: 弹幕内容
        type: string
      timestamp:
        description: 弹幕出现的时间戳
        type: integer
    type: object
  types.GetCommentResp:
    properties:
      avatar:
        description: 用户头像
        type: string
      content:
        description: 评论内容
        type: string
      create_date:
        description: 评论发布日期，格式 mm-dd
        type: string
      user_name:
        description: 用户名
        type: string
    type: object
  types.GetFavResp:
    properties:
      author_name:
        description: 视频作者
        type: integer
      category_id:
        description: 视频所属领域
        type: string
      collection_count:
        description: 视频总收藏数
        type: integer
      cover_url:
        description: 视频封面地址
        type: string
      create_time:
        description: 视频创建时间
        type: string
      favorite_count:
        description: 视频的点赞总数
        type: integer
      title:
        description: 视频标题
        type: string
    type: object
  types.GetFavlistResp:
    properties:
      collection_name:
        description: 收藏夹名
        type: string
      create_time:
        type: string
      favlist:
        items:
          $ref: '#/definitions/types.GetFavResp'
        type: array
      total:
        type: integer
      user_name:
        description: 收藏夹创建人
        type: string
    type: object
  types.GetFavoriteResp:
    properties:
      author_name:
        description: 视频作者
        type: integer
      collection_count:
        description: 播放总数
        type: integer
      cover_url:
        description: 视频封面地址
        type: string
      title:
        description: 视频标题
        type: string
    type: object
  types.Response:
    properties:
      data: {}
      error:
        type: string
      msg:
        type: string
      status:
        type: integer
    type: object
  types.VideoUpdatePublish:
    properties:
      category_id:
        description: 视频所属领域
        type: string
      title:
        description: 视频标题
        type: string
      video_id:
        description: 视频id
        type: string
    type: object
host: localhost:8811
info:
  contact:
    url: https://github.com/swaggo/swag/blob/master/README_zh-CN.md
  description: This is cxy api docs.
  license:
    name: Apache 2.0
  title: 视频 API
  version: "1.0"
paths:
  /interaction/barrage:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单提交获取弹幕
      operationId: GetBarrage
      parameters:
      - description: 视频id
        in: query
        name: VideoId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetBarrageResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 弹幕获取
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单提交弹幕
      operationId: Barrage
      parameters:
      - description: ' 弹幕所属视频的ID'
        in: formData
        name: VideoID
        required: true
        type: integer
      - description: 弹幕内容
        in: formData
        name: Content
        required: true
        type: string
      - description: 弹幕颜色
        in: formData
        name: Color
        required: true
        type: string
      - description: 弹幕出现的时间戳
        in: formData
        name: Timestamp
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 弹幕发送
  /interaction/comment:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单提交查看评论列表
      operationId: GetComment
      parameters:
      - description: 视频id
        in: query
        name: VideoId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetCommentResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 视频评论列表
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单提交创建评论
      operationId: CommentCreateReq
      parameters:
      - description: 视频id
        in: formData
        name: VideoId
        required: true
        type: integer
      - description: 内容
        in: formData
        name: Content
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 创建评论
  /interaction/fav:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单提交将视频移除收藏夹
      operationId: FavlistDel
      parameters:
      - description: 收藏夹id
        in: formData
        name: FavlistId
        required: true
        type: string
      - description: 视频id
        in: formData
        name: VideoId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 视频移除收藏夹
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单提交将视频加入收藏夹
      operationId: FavlistAdd
      parameters:
      - description: 想要添加的视频id和文件夹id
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.FavlistAddReq'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 加入收藏夹
  /interaction/favlist:
    delete:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单提交删除收藏夹
      operationId: DelFavlist
      parameters:
      - description: 收藏夹id
        in: formData
        name: FavlistId
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 删除收藏夹
    get:
      consumes:
      - application/json
      description: 通过表单提交方式查看收藏夹
      parameters:
      - description: 用户id
        in: query
        name: uid
        required: true
        type: integer
      - description: 收藏夹id
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetFavlistResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/api.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 查看收藏夹
      tags:
      - 交互
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单提交创建收藏夹
      operationId: FavlistCreate
      parameters:
      - description: 收藏夹名称
        in: formData
        name: FavlistName
        required: true
        type: string
      - description: 收藏夹类型，1为公开 2为隐藏
        in: formData
        name: Type
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 创建收藏夹
  /interaction/favorite:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单提交方式查看喜欢列表
      operationId: GetFavorite
      parameters:
      - description: 用户id
        in: query
        name: UserId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetFavoriteResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 喜欢列表
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单提交点赞/取消赞
      operationId: Favorite
      parameters:
      - description: 视频id
        in: formData
        name: VideoId
        required: true
        type: integer
      - description: 1点赞 2取消
        in: formData
        name: Type
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 点赞/取消赞
  /user/action:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单提交进行关注/取关
      operationId: UserAction
      parameters:
      - description: 对方用户id
        in: formData
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 用户关注/取关
  /user/login:
    post:
      consumes:
      - application/json
      description: 通过对方id和我的token获取对方用户信息
      operationId: UserInfo
      parameters:
      - description: 对方用户ID
        in: query
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 用户信息
  /user/register:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单提交创建用户
      operationId: UserRegister
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 创建用户
  /video/channel:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单提交获取该分类的视频
      operationId: VideoChannel
      parameters:
      - description: 分类id
        in: query
        name: channel_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetFavResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 视频分类
  /video/publish/action:
    post:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单提交创建用户
      operationId: VideoCreate
      parameters:
      - description: 用户名
        in: formData
        name: username
        required: true
        type: string
      - description: 密码
        in: formData
        name: password
        required: true
        type: string
      - description: 封面
        in: formData
        name: image
        type: file
      - description: 视频
        in: formData
        name: video
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 创上传视频
    put:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单提交用户发布的视频
      operationId: VideoUpdatePublish
      parameters:
      - description: 更新后的视频信息
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/types.VideoUpdatePublish'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.Response'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 用户视频更新
  /video/publish/list:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单获取该用户发布的视频
      operationId: VideoGetPublish
      parameters:
      - description: 用户id
        in: query
        name: user_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetFavResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 用户视频列表
  /video/search:
    get:
      consumes:
      - application/x-www-form-urlencoded
      description: 通过表单提交进行视频搜索
      operationId: VideoSearch
      parameters:
      - description: 关键字
        in: query
        name: text
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/types.GetFavResp'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/api.ErrorResponse'
      summary: 视频搜索
swagger: "2.0"
